// Single source of truth for the Item column mapping (db column <-> JSON/JS
// field name <-> type), mirroring com.antontech.itemkafka_poc.model.Item
// from the Spring Boot POC. Every other layer (model, repository, Flink-style
// jobs) derives its behaviour from this one array instead of hand-rolling
// 80+ getters/setters/prepared-statement bindings like the Java version does.
//
// type values:
//   'string'   -> VARCHAR/CHAR column, JS string
//   'int'      -> INT column, JS number (integer)
//   'long'     -> BIGINT column, JS number
//   'decimal'  -> DECIMAL column, JS number (string-safe)
//   'datetime' -> DATETIME column, JS Date / ISO string
//   'char'     -> CHAR(1) column, JS single-character string

const ITEM_COLUMNS = [
  { db: 'item_id', js: 'itemId', type: 'string', pk: true, default: null },
  { db: 'item_level', js: 'itemLevel', type: 'int', default: 0 },
  { db: 'item_number_type', js: 'itemNumberType', type: 'string', default: 'UNKNOWN' },
  { db: 'prefix', js: 'prefix', type: 'int', default: 0 },
  { db: 'allocator_system', js: 'allocatorSystem', type: 'string', default: 'DEFAULT' },
  { db: 'business_unit_id', js: 'businessUnitId', type: 'int', default: 0 },
  { db: 'catch_weight_ind', js: 'catchWeightInd', type: 'string', default: 'N' },
  { db: 'class_id', js: 'classId', type: 'int', default: 0 },
  { db: 'colour_dsc', js: 'colourDsc', type: 'string', default: null },
  { db: 'colour_group_id', js: 'colourGroupId', type: 'string', default: 'None' },
  { db: 'colour_id', js: 'colourId', type: 'string', default: 'UNKNOWN' },
  { db: 'colour_range_id', js: 'colourRangeId', type: 'int', default: 0 },
  { db: 'company_id', js: 'companyId', type: 'int', default: 0 },
  { db: 'count_on_us_id', js: 'countOnUsId', type: 'string', default: null },
  { db: 'create_dte', js: 'createDte', type: 'datetime', default: () => new Date() },
  { db: 'dept_id', js: 'deptId', type: 'int', default: 0 },
  { db: 'discipline', js: 'discipline', type: 'string', default: null },
  { db: 'domain_id', js: 'domainId', type: 'int', default: 0 },
  { db: 'flavour_dsc', js: 'flavourDsc', type: 'string', default: null },
  { db: 'flavour_group_id', js: 'flavourGroupId', type: 'string', default: null },
  { db: 'flavour_id', js: 'flavourId', type: 'string', default: null },
  { db: 'flavour_range_id', js: 'flavourRangeId', type: 'int', default: 0 },
  { db: 'forecast_ind', js: 'forecastInd', type: 'string', default: 'N' },
  { db: 'free_range_id', js: 'freeRangeId', type: 'string', default: null },
  { db: 'from_temp', js: 'fromTemp', type: 'int', default: 0 },
  { db: 'group_id', js: 'groupId', type: 'int', default: 0 },
  { db: 'high_max_temp', js: 'highMaxTemp', type: 'int', default: 0 },
  { db: 'high_min_temp', js: 'highMinTemp', type: 'int', default: 0 },
  { db: 'item_grandparent', js: 'itemGrandparent', type: 'string', default: null },
  { db: 'item_parent', js: 'itemParent', type: 'string', default: null },
  { db: 'kidz_id', js: 'kidzId', type: 'string', default: null },
  { db: 'orderable_ind', js: 'orderableInd', type: 'string', default: 'N' },
  { db: 'pack_ind', js: 'packInd', type: 'string', default: 'N' },
  { db: 'pack_member', js: 'packMember', type: 'string', default: null },
  { db: 'pack_qty', js: 'packQty', type: 'decimal', default: 0 },
  { db: 'phase_id', js: 'phaseId', type: 'int', default: 1 },
  { db: 'price_mark_ind', js: 'priceMarkInd', type: 'string', default: 'N' },
  { db: 'primary_ref_item_ind', js: 'primaryRefItemInd', type: 'string', default: 'N' },
  { db: 'primary_size_dsc', js: 'primarySizeDsc', type: 'string', default: null },
  { db: 'primary_size_group_id', js: 'primarySizeGroupId', type: 'string', default: null },
  { db: 'primary_size_id', js: 'primarySizeId', type: 'string', default: null },
  { db: 'primary_size_range_id', js: 'primarySizeRangeId', type: 'int', default: 0 },
  { db: 'product_group_scaling', js: 'productGroupScaling', type: 'string', default: null },
  { db: 'product_id', js: 'productId', type: 'string', default: null },
  { db: 'reference_item_ind', js: 'referenceItemInd', type: 'string', default: 'N' },
  { db: 'scent_dsc', js: 'scentDsc', type: 'string', default: null },
  { db: 'scent_group_id', js: 'scentGroupId', type: 'string', default: null },
  { db: 'scent_id', js: 'scentId', type: 'string', default: null },
  { db: 'scent_range_id', js: 'scentRangeId', type: 'int', default: 0 },
  { db: 'season_id', js: 'seasonId', type: 'int', default: 0 },
  { db: 'secondary_size_dsc', js: 'secondarySizeDsc', type: 'string', default: null },
  { db: 'secondary_size_group_id', js: 'secondarySizeGroupId', type: 'string', default: null },
  { db: 'secondary_size_id', js: 'secondarySizeId', type: 'string', default: null },
  { db: 'secondary_size_range_id', js: 'secondarySizeRangeId', type: 'int', default: 0 },
  { db: 'sellable_ind', js: 'sellableInd', type: 'string', default: 'N' },
  { db: 'short_dsc', js: 'shortDsc', type: 'string', default: 'N/A' },
  { db: 'simple_pack_ind', js: 'simplePackInd', type: 'string', default: 'N' },
  { db: 'size_profile_ind', js: 'sizeProfileInd', type: 'string', default: 'N' },
  { db: 'standard_uom', js: 'standardUom', type: 'string', default: 'EA' },
  { db: 'status', js: 'status', type: 'string', default: 'A' },
  { db: 'sub_group_id', js: 'subGroupId', type: 'int', default: 0 },
  { db: 'subclass_id', js: 'subclassId', type: 'int', default: 0 },
  { db: 'supplier_no', js: 'supplierNo', type: 'int', default: 0 },
  { db: 'to_temp', js: 'toTemp', type: 'int', default: 0 },
  { db: 'tran_ind', js: 'tranInd', type: 'string', default: 'N' },
  { db: 'tran_level', js: 'tranLevel', type: 'int', default: 0 },
  { db: 'std_colour', js: 'stdColour', type: 'string', default: 'UNKNOWN' },
  { db: 'std_size', js: 'stdSize', type: 'string', default: 'UNKNOWN' },
  { db: 'std_static_mass', js: 'stdStaticMass', type: 'decimal', default: 0 },
  { db: 'std_style', js: 'stdStyle', type: 'string', default: () => require('uuid').v4() },
  { db: 'std_style_colour', js: 'stdStyleColour', type: 'string', default: 'UNKNOWN' },
  { db: 'variable_weight_ind', js: 'variableWeightInd', type: 'char', default: 'N' },
  { db: 'loose_prod_ind', js: 'looseProdInd', type: 'char', default: 'N' },
  { db: 'item_scale_ind', js: 'itemScaleInd', type: 'char', default: 'N' },
  { db: 'legacy_sku_no', js: 'legacySkuNo', type: 'string', default: 'N/A' },
  { db: 'legacy_random_mass_ind', js: 'legacyRandomMassInd', type: 'char', default: 'N' },
  { db: 'legacy_vat_ind', js: 'legacyVatInd', type: 'char', default: 'N' },
  { db: 'action_ind', js: 'actionInd', type: 'char', default: 'N' },
  { db: 'extract_seq_no', js: 'extractSeqNo', type: 'long', default: 0 },
  { db: 'vat_cde', js: 'vatCde', type: 'string', default: 'S' },
  { db: 'vat_rate', js: 'vatRate', type: 'decimal', default: 0 },
  { db: 'source_system', js: 'sourceSystem', type: 'string', default: 'UNKNOWN' },
  { db: 'vpn_no', js: 'vpnNo', type: 'string', default: 'N/A' },
  { db: 'ext_ref_no', js: 'extRefNo', type: 'string', default: 'N/A' },
  { db: 'item_long_desc', js: 'itemLongDesc', type: 'string', default: 'No Description' },
  { db: 'segregation_ind', js: 'segregationInd', type: 'string', default: 'N' },
  { db: 'prod_class', js: 'prodClass', type: 'string', default: 'N/A' },
  { db: 'last_update_dte', js: 'lastUpdateDte', type: 'datetime', default: () => new Date() },
];

module.exports = { ITEM_COLUMNS };

